name: Docker squid proxy

on: [push]

jobs:

  deploy:

    runs-on: ubuntu-latest
    env:
      PORT: 3128

    steps:
    - uses: actions/checkout@v1
    - name: Build the container image
      run: docker run --name squid -d --restart=always --publish ${PORT}:3128 -v ${GITHUB_WORKSPACE}/squid.passwd:/etc/squid/passwd -v ${GITHUB_WORKSPACE}/squid.conf:/etc/squid/squid.conf sameersbn/squid:3.5.27-2
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs squid